import { Encomenda, Visitante, Unidade } from './types';

// Unidades iniciais do condomínio
export const INITIAL_UNIDADES: Unidade[] = [
  { id: 'u-1', bloco: 'A', numero: '101', tipo: 'APARTAMENTO', moradores: ['Mariana Fernandes', 'Gabriel Fernandes'] },
  { id: 'u-2', bloco: 'A', numero: '102', tipo: 'APARTAMENTO', moradores: ['Juliana Moreira'] },
  { id: 'u-3', bloco: 'A', numero: '201', tipo: 'APARTAMENTO', moradores: ['Rodrigo Vasconcelos', 'Beatriz Lima'] },
  { id: 'u-4', bloco: 'B', numero: '101', tipo: 'APARTAMENTO', moradores: ['Felipe Antunes'] },
  { id: 'u-5', bloco: 'B', numero: 'PH01', tipo: 'COBERTURA', moradores: ['Roberto Albuquerque (Síndico)'] },
];

// Encomendas iniciais
export const INITIAL_ENCOMENDAS: Encomenda[] = [
  {
    id: 'enc-1',
    unidade_id: 'u-1',
    unidade_bloco: 'A',
    unidade_numero: '101',
    morador_nome: 'Mariana Fernandes',
    morador_telefone: '(11) 96543-2109',
    codigo_barras_qrcode: 'PKG-AMZ-789456123BR',
    transportadora: 'Amazon Logística',
    codigo_rastreio: 'BR789456123AMZ',
    descricao_pacote: 'Caixa Média (Eletrônicos)',
    foto_comprovante_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=500&auto=format&fit=crop&q=60',
    status: 'AGUARDANDO_RETIRADA',
    data_recebimento: new Date(Date.now() - 3600000 * 2).toISOString(),
    porteiro_recebedor_nome: 'João Portaria',
  },
  {
    id: 'enc-2',
    unidade_id: 'u-5',
    unidade_bloco: 'B',
    unidade_numero: 'PH01',
    morador_nome: 'Roberto Albuquerque',
    morador_telefone: '(11) 95432-1098',
    codigo_barras_qrcode: 'PKG-ML-987654321BR',
    transportadora: 'Mercado Livre Express',
    codigo_rastreio: 'MLB987654321',
    descricao_pacote: 'Envelope Documento Urgente',
    foto_comprovante_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=500&auto=format&fit=crop&q=60',
    status: 'AGUARDANDO_RETIRADA',
    data_recebimento: new Date(Date.now() - 3600000 * 5).toISOString(),
    porteiro_recebedor_nome: 'João Portaria',
  },
  {
    id: 'enc-3',
    unidade_id: 'u-3',
    unidade_bloco: 'A',
    unidade_numero: '201',
    morador_nome: 'Rodrigo Vasconcelos',
    morador_telefone: '(11) 94321-0987',
    codigo_barras_qrcode: 'PKG-SHP-112233445BR',
    transportadora: 'Shopee Express',
    codigo_rastreio: 'SHP112233445',
    descricao_pacote: 'Pacote Roupas / Vestuário',
    status: 'RETIRADO',
    data_recebimento: new Date(Date.now() - 3600000 * 24).toISOString(),
    data_retirada: new Date(Date.now() - 3600000 * 3).toISOString(),
    retirado_por_nome: 'Rodrigo Vasconcelos (Titular)',
    retirado_por_documento: '44.555.666-7',
    porteiro_recebedor_nome: 'Carlos Plantão',
  },
  {
    id: 'enc-4',
    unidade_id: 'u-2',
    unidade_bloco: 'A',
    unidade_numero: '102',
    morador_nome: 'Juliana Moreira',
    morador_telefone: '(11) 93210-9876',
    codigo_barras_qrcode: 'PKG-COR-556677889BR',
    transportadora: 'Correios (Sedex)',
    codigo_rastreio: 'SZ556677889BR',
    descricao_pacote: 'Caixa Pequena Farmácia',
    status: 'AGUARDANDO_RETIRADA',
    data_recebimento: new Date(Date.now() - 3600000 * 8).toISOString(),
    porteiro_recebedor_nome: 'João Portaria',
  }
];

// Visitantes iniciais
export const INITIAL_VISITANTES: Visitante[] = [
  {
    id: 'vis-1',
    nome_completo: 'Lucas Mendes de Oliveira',
    cpf: '555.666.777-88',
    telefone: '(11) 98888-7777',
    foto_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&auto=format&fit=crop&q=80',
    tipo: 'VISITANTE',
    unidade_destino_bloco: 'A',
    unidade_destino_numero: '101',
    placa_veiculo: 'BRA2E19',
    ativo: true,
    status_acesso: 'DENTRO',
    data_cadastro: new Date(Date.now() - 3600000 * 2).toISOString(),
    hora_entrada: '14:30',
    observacoes: 'Familiar da moradora Mariana (autorizado para almoço)',
  },
  {
    id: 'vis-2',
    nome_completo: 'Paulo Santos (Eletricista)',
    cpf: '666.777.888-99',
    telefone: '(11) 97777-6666',
    foto_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400&auto=format&fit=crop&q=80',
    tipo: 'PRESTADOR_SERVICO',
    empresa: 'EletroFix Instalações',
    unidade_destino_bloco: 'B',
    unidade_destino_numero: 'PH01',
    placa_veiculo: 'ABC1D23',
    ativo: true,
    status_acesso: 'DENTRO',
    data_cadastro: new Date(Date.now() - 3600000 * 4).toISOString(),
    hora_entrada: '11:15',
    observacoes: 'Manutenção de quadro de disjuntores da cobertura',
  },
  {
    id: 'vis-3',
    nome_completo: 'Bruno Entregador',
    telefone: '(11) 96666-5555',
    foto_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    tipo: 'ENTREGADOR',
    empresa: 'iFood / Mercado Pago',
    placa_veiculo: 'XYZ9K88',
    ativo: true,
    status_acesso: 'CONCLUIDO',
    data_cadastro: new Date(Date.now() - 3600000 * 6).toISOString(),
    hora_entrada: '10:00',
    observacoes: 'Entrega rápida de refeição',
  }
];
